version: "3.9"
services:
  api:
    image: chatchaisteelbestbuy/8.2.7-apache-buster
#    build: api/.
    volumes:
      - ./api:/var/www/html:cache
    ports:
      - "9000:80"
    links:
      - database
    restart: always

#  vue:
#    build: ./learning-vue
#    command: npm run dev
#    volumes:
#      - ./learning-vue:/app
#      - /learning-vue/app/node_modules
#    ports:
#      - "3333:3333"

  #  redis:
  #    container_name: redis
  #    image: redis:4-alpine
  #    ports:
  #      - "16379:6379"
  #    volumes:
  #      - ./redis:/data

#  nginx:
#    image: nginx:1.21.0
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx-config/conf.d:/etc/nginx/conf.d:ro
#      - ./nginx-config/ssl:/etc/nginx/ssl:ro
#    links:
#      - api
#    restart: always

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1stlogin
    ports:
      - 3306:3306
    hostname: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql